export const DEFAULT_POST_MM = 43;
export const DEFAULT_OPENING_MM = 283;
export const DEFAULT_ROW_HEIGHT_MM = 120;

export const DEFAULT_PATTERN_SEGMENTS = [
  DEFAULT_POST_MM,
  DEFAULT_OPENING_MM,
  DEFAULT_POST_MM,
  DEFAULT_POST_MM,
  DEFAULT_OPENING_MM,
  DEFAULT_POST_MM,
  DEFAULT_POST_MM
];

export const DEFAULT_PATTERN_TEXT = DEFAULT_PATTERN_SEGMENTS.join(',');
